### ISSUE TITLE
Use some dependency injection library

### ISSUE THREAD

**Issue by reo7sp** [bender-wardrobe/Recast#11]

**Comment by LionZXY** [comment]
@reo7sp Зачем? Какие есть на примете?

**Comment by reo7sp** [comment]
Зачем:
1. Это удобно (по крайней мере в Джаве точно оч удобно получается).
2. Изи баллы за паттерны.

Либы на примете:
Пока нет. 1 июня или раньше займусь Рекастом.

**Comment by LionZXY** [comment]
Я одназночно за. Ещё можно посмотреть в сторону реактивного программирования

**Comment by reo7sp** [comment]
мяу

**Comment by LionZXY** [comment]
@reo7sp Кыс-кыс

**Comment by StealthTech** [comment]
Ребята, у вас всё хорошо?)

**Comment by reo7sp** [comment]
нормалёк

**Comment by reo7sp** [comment]
https://github.com/ybainier/Hypodermic/wiki/Getting-started

**Comment by reo7sp** [comment]
Да не, boost.di таки норм http://boost-experimental.github.io/di/index.html
