### ISSUE TITLE
Сделать сеть

### ISSUE THREAD

**Issue by LionZXY** [bender-wardrobe/Recast#3]
Прописать логику обмена пакетами, свой протокол поверх UDP, продумать когда и как будут синхронизироваться клиент и сервер
![image](https://cloud.githubusercontent.com/assets/5871715/23835839/4383863e-077f-11e7-8b67-98a49400b22d.png)

**Comment by LionZXY** [comment]
Еще входит консольный клиент

**Comment by LionZXY** [comment]
![image](https://cloud.githubusercontent.com/assets/5871715/24334270/2802b41a-1270-11e7-92d8-d1c4fe5f5d5d.png)

**Comment by StealthTech** [comment]
Rewrite client part on c# (Unity integration)

**Comment by LionZXY** [comment]
Надо будет еще сделать урезанную версию сервера. С твоей стороны надо сделать еще синхронизацию обьектов. 
Т.е. отображение каждый тик лезет в локальный сервер и берет оттуда обьекты
А в свою очередь локальный сервер в фоновом режиме сверяет данные с сервером и отсылает новые события. Сама синхронизация происходит в фоновом потоке и используется модель репликации, как на "взрослом", удаленном, сервере. Если какие-то вопросы, пиши
```
           Удаленный сервер
                  | <- сеть, синхронизация
Клиент <-> Мини-сервер
```

**Comment by LionZXY** [comment]
Возможно, на первое время никакого мини-сервера не нужно и клиент сразу будет ходить на сервер но сама вот это архитектура должна сохраняться (C# -> C++ (клиент) -> С++ (сервер))

**Comment by StealthTech** [comment]
То есть, клиент на c++ остаётся всё-таки? Не переписывать на c#, а добавить прослойку?

**Comment by LionZXY** [comment]
На C# всеравно придется писать. Нужно же как-то пихать данные в клиент

**Comment by StealthTech** [comment]
Я представляю, что на c# придётся писать - вопрос не в этом. Я оставляю часть клиента на c++, которую сейчас написал, и дописываю на c#, чтобы как-то ему передавать данные. Я правильно понял?

**Comment by LionZXY** [comment]
Да. И забирать

**Comment by StealthTech** [comment]
Принято!

**Comment by LionZXY** [comment]
Получается что Клиент и Минисервер будут передавать друг другу одни данные (положение блока 1, положение блока 2, файрбол), а минисервер и удаленный сервер другие, уже более низкоуровневые (смещение блока, изменение карты температуры)

**Comment by LionZXY** [comment]
#54
