### ISSUE TITLE
ChunkedWorld компонента

### ISSUE THREAD

**Issue by reo7sp** [bender-wardrobe/Recast#35]
- [x] Фабрика чанков
- [x] Никаких темплейтов с конкретными типами!
- [x] Updater

**Comment by LionZXY** [comment]
Можно подробнее по каждому пункту?)

**Comment by LionZXY** [comment]
У Box2d есть свой world, к которому привязываются Entity. Может ну нафиг свой мир?

**Comment by reo7sp** [comment]
>Можно подробнее по каждому пункту?)

Эт я для себя
